# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.product import Product
from openapi_server import util

from openapi_server.models.product import Product  # noqa: E501

class GetAllProducts200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, offset=None, limit=None, total=None, data=None):  # noqa: E501
        """GetAllProducts200Response - a model defined in OpenAPI

        :param offset: The offset of this GetAllProducts200Response.  # noqa: E501
        :type offset: int
        :param limit: The limit of this GetAllProducts200Response.  # noqa: E501
        :type limit: int
        :param total: The total of this GetAllProducts200Response.  # noqa: E501
        :type total: int
        :param data: The data of this GetAllProducts200Response.  # noqa: E501
        :type data: List[Product]
        """
        self.openapi_types = {
            'offset': int,
            'limit': int,
            'total': int,
            'data': List[Product]
        }

        self.attribute_map = {
            'offset': 'offset',
            'limit': 'limit',
            'total': 'total',
            'data': 'data'
        }

        self._offset = offset
        self._limit = limit
        self._total = total
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetAllProducts200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getAllProducts_200_response of this GetAllProducts200Response.  # noqa: E501
        :rtype: GetAllProducts200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def offset(self):
        """Gets the offset of this GetAllProducts200Response.

        Page offset  # noqa: E501

        :return: The offset of this GetAllProducts200Response.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this GetAllProducts200Response.

        Page offset  # noqa: E501

        :param offset: The offset of this GetAllProducts200Response.
        :type offset: int
        """

        self._offset = offset

    @property
    def limit(self):
        """Gets the limit of this GetAllProducts200Response.

        Page size limit  # noqa: E501

        :return: The limit of this GetAllProducts200Response.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this GetAllProducts200Response.

        Page size limit  # noqa: E501

        :param limit: The limit of this GetAllProducts200Response.
        :type limit: int
        """

        self._limit = limit

    @property
    def total(self):
        """Gets the total of this GetAllProducts200Response.

        Total number of records across all pages  # noqa: E501

        :return: The total of this GetAllProducts200Response.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this GetAllProducts200Response.

        Total number of records across all pages  # noqa: E501

        :param total: The total of this GetAllProducts200Response.
        :type total: int
        """

        self._total = total

    @property
    def data(self):
        """Gets the data of this GetAllProducts200Response.


        :return: The data of this GetAllProducts200Response.
        :rtype: List[Product]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GetAllProducts200Response.


        :param data: The data of this GetAllProducts200Response.
        :type data: List[Product]
        """

        self._data = data
